_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p67_res2net_fpn_backbone"
  WEIGHTS: "output/CenterNet2/CenterNet2_R2-101-DCN_896_diou/best.pth"
  RESNETS:
    DEPTH: 101
    WIDTH_PER_GROUP: 26
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  CENTERNET:
    USE_DEFORMABLE: True
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4"]
INPUT:
  FORMAT: RGB
TEST:
  EVAL_PERIOD: 360
SOLVER:
  MAX_ITER: 3600
  CHECKPOINT_PERIOD: 360
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.001
  IMS_PER_BATCH: 4
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 896
